USE retail_sales_project;

# Q1. What is the total sales and total profit generated by the company?
SELECT ROUND(SUM(Sales), 3) AS Total_Sales, 
	   ROUND(SUM(Profit), 3) AS Total_Profit,
       ROUND((ROUND(SUM(Profit), 3) / ROUND(SUM(Sales), 3)) * 100, 3) AS Profit_Margin
FROM Superstore;

# Q2. Which region generates the highest sales?
SELECT Region, 
       ROUND(SUM(Sales), 3) AS Total_Sales,
	   ROUND((SUM(Sales) /SUM(SUM(Sales)) OVER()) * 100, 3) AS Sales_Contribution
FROM Superstore
GROUP BY Region
ORDER BY Total_Sales DESC;

# Q3. Which State generates the highest profit?
SELECT State,
       ROUND(SUM(Profit), 3) AS Total_Profit,
       ROUND((SUM(Profit)/SUM(SUM(Profit)) OVER()) * 100, 3) AS Profit_Contribution
FROM Superstore
GROUP BY State
ORDER BY Total_Profit DESC;

# Q3.1. finding the loss incuring States
SELECT State,
       SUM(Profit) AS Total_Profit
FROM Superstore
GROUP BY State
HAVING SUM(Profit) < 0;

# Q3.2. finding the number of loss incuring States
SELECT COUNT(*) AS Number_of_Loss_incuring_States
FROM (SELECT State,
             SUM(Profit) AS Total_Profit
      FROM Superstore
      GROUP BY State
      HAVING SUM(Profit) < 0 ) AS Loss_Table;
      
# Q4. What is the sales contribution of each category?
SELECT Category, 
       ROUND(SUM(Sales), 3) AS Total_Sales,
	   ROUND((SUM(Sales) /SUM(SUM(Sales)) OVER()) * 100, 3) AS Sales_Contribution
FROM Superstore
GROUP BY Category
ORDER BY Total_Sales DESC;

# Q4.1. checking if Sales are translating to Profits
SELECT Category, 
       ROUND(SUM(Profit), 3) AS Total_Profit,
	   ROUND((SUM(Profit) /SUM(SUM(Profit)) OVER()) * 100, 3) AS Profit_Contribution
FROM Superstore
GROUP BY Category
ORDER BY Total_Profit DESC;

# Q4.2. Which furniture sub-category is responsible for low profitability
SELECT Category, `Sub-Category`, 
       ROUND(SUM(Profit), 3) AS Total_Profit,
	   ROUND((SUM(Profit) /SUM(SUM(Profit)) OVER()) * 100, 3) AS Profit_Contribution
FROM Superstore
GROUP BY Category, `Sub-Category`
HAVING Category = 'Furniture'
ORDER BY Total_Profit DESC;

# Q5. Which customer segment contributes to highest sales?
SELECT Segment,
       ROUND(SUM(Sales), 3) AS Total_Sales,
       ROUND((SUM(Sales)/ SUM(SUM(Sales)) OVER()) * 100 , 3) AS Sales_Contribution
FROM Superstore
GROUP BY Segment
ORDER BY Total_Sales DESC;

# Q5.1. checking if Sales are translating to Profits
SELECT Segment, 
       ROUND(SUM(Profit), 3) AS Total_Profit,
	   ROUND((SUM(Profit) /SUM(SUM(Profit)) OVER()) * 100, 3) AS Profit_Contribution
FROM Superstore
GROUP BY Segment
ORDER BY Total_Profit DESC;

# Q6. Which Sub-Categories generate the highest profit?
SELECT Category,`Sub-Category`, 
       ROUND(SUM(Profit), 3) AS Total_Profit,
	   ROUND((SUM(Profit) /SUM(SUM(Profit)) OVER()) * 100, 3) AS Profit_Contribution
FROM Superstore
GROUP BY Category, `Sub-Category`
ORDER BY Total_Profit DESC;

# Q7. Which Sub-Category generates losses?
# Q7.1. Which Sub-Category generates losses when loss transcations are considered?
SELECT Category, 
       `Sub-Category`,
       ROUND(SUM(Profit), 3) AS Total_Loss,
       ROUND((SUM(Profit) /SUM(SUM(Profit)) OVER()) * 100, 3) AS Loss_Contribution
FROM Superstore
WHERE Profit < 0
GROUP BY Category, `Sub-Category`
HAVING SUM(Profit) < 0
ORDER BY Total_Loss;

# Q7.2. Which Sub-Category generates losses over all?
SELECT Category, 
       `Sub-Category`,
       ROUND(SUM(Profit), 3) AS Total_Loss,
       ROUND((SUM(Profit) /SUM(SUM(Profit)) OVER()) * 100, 3) AS Loss_Contribution
FROM Superstore
GROUP BY Category, `Sub-Category`
HAVING SUM(Profit) < 0
ORDER BY Total_Loss;

# Q8. How does discount affect profit?
SELECT Discount,
       ROUND(SUM(Sales), 3) AS Total_Sales,
	   ROUND(SUM(Profit), 3) AS Total_Profit,
       ROUND((SUM(Profit) * 100/ SUM(Sales)) , 3) AS Profit_Margin
FROM Superstore
GROUP BY Discount
ORDER BY Discount;

# Q8.1. Which category gives more discounts
SELECT Category,
       ROUND(SUM(Discount) * 100 /SUM(SUM(Discount)) OVER(), 3)  AS Total_Discount,
       ROUND(SUM(Sales) * 100 /SUM(SUM(Sales)) OVER(), 3) AS Total_Sales,
       ROUND(SUM(Profit) * 100 /SUM(SUM(Profit)) OVER(), 3) AS Total_Profit
FROM Superstore
GROUP BY Category
ORDER BY Total_Discount DESC;

# Q9. Which top 10 cities generate the highest sales?
SELECT City, State, 
       ROUND(SUM(Sales), 3) AS Total_Sales,
       ROUND(SUM(Sales) * 100 /SUM(SUM(Sales)) OVER(),3) AS Sales_Contribution
FROM Superstore
GROUP BY City, State
ORDER BY Total_Sales DESC
LIMIT 10;

# Q10. Which region has the highest profit margin?
SELECT Region, 
       ROUND(SUM(Profit), 3) AS Total_Profit,
       ROUND(SUM(Sales), 3) AS Total_Sales,
       ROUND(SUM(Discount) * 100 /SUM(SUM(Discount)) OVER() , 3) AS Discount_Contribution,
	   ROUND(SUM(Profit) * 100 /SUM(Sales) , 3) AS Profit_Margin
FROM Superstore
GROUP BY Region
ORDER BY Profit_Margin DESC;
